services:
  postgres:
    image: postgres:18
    container_name: workshop_todolist_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql
    ports:
      - "${DB_PORT}:5432"
    restart: always

  app:
    build: .
    container_name: workshop_nest-app
    environment:
      DATABASE_URL: "postgresql://postgres:dm271146@postgres:5432/workshop_todolist_postgres"
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    restart: always

volumes:
  pgdata:
